name: digitalridr
description: "An Apartment and Travel Booking App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Http library
  http: 1.5.0

  # iOS-style icons
  cupertino_icons: 1.0.8

  # Splash screen
  flutter_native_splash: 2.4.7
  animated_splash_screen: 1.3.0
  lottie: 3.3.2

  # Local storage
  shared_preferences: 2.5.3

  # State management
  provider: 6.1.5

  # UI utilities
  material_color_utilities: 0.11.1
  google_fonts: 6.3.2
  carousel_slider: 5.1.1

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  shimmer_animation: ^2.2.2
  connectivity_plus: ^7.0.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: 1.4.0
  launcher_name: 1.0.2
  flutter_launcher_icons: 0.14.1
  flutter_lints: 3.0.2  # moved here and fixed indentation

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/company/app_icon.png"

launcher_name:
  default: "DigitalRidr"

flutter_native_splash:
  android: true
  ios: true
  web: false

  image: "assets/company/icon_400x400_enlarged.png"
  branding: "assets/company/company_name_1000x250.png"
  color: "#F9F9F9"


  image_dark: "assets/company/icon_400x400_enlarged.png"
  branding_dark: "assets/company/company_name_1000x250.png"
  color_dark: "#1E272C"

  android_12:
    image: "assets/company/icon_400x400_enlarged.png"
    branding: "assets/company/company_name_1000x250.png"
    color: "#F9F9F9"

    image_dark: "assets/company/icon_400x400_enlarged.png"
    branding_dark: "assets/company/company_name_1000x250.png"
    color_dark: "#1E272C"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/company/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: DigitalridrAppIcons
      fonts:
        - asset: fonts/digitalridr_icon_font.ttf

    - family: QuickSand
      fonts:
        - asset: fonts/quicksand_bold.ttf

    - family: IndieFlower
      fonts:
        - asset: fonts/indieflower_regular.ttf

    - family: Antic
      fonts:
        - asset: fonts/antic_.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
